# /etc/guvnor/services/identity.yaml

defaults:
  image: ghcr.io/krystal/identity
  imageTag: latest
  env:
    RAILS_ENV: production
    SECRET_KEY_BASE: abcdef1234567890
  mounts:
    - host: /opt/identity/config.yml
      container: /config.yml

processes:
  web:
    command: ["bin/rails", "server"]
    quantity: 1
    restartMode: standard
    privileged: true
    env:
      HOSTNAME: identity.k.io
    caddy:
      hostnames:
        - identity.k.io
        - identity.another.domain
    readyChecks:
      frequency: 2
      timeout: 5
      maximum: 30
      http:
        expectedStatus: 200
        path: /login
        headers:
          - name: Host
            value: identity.k.io
      command:
        command: ["stat" "/ready.txt"]
        expectedExitCode: 0

  worker:
    command: ["bin/rake", "worker"]
    quantity: 4
    restartMode: rolling
  
  cron:
    command: ["bin/rake", "cron"]
    restartMode: replace
    network:
      mode: host # or 'default'
      containerPort: 8080 # not for host networking

tasks:
  console:
    command: ["bin/rails", "console"]
    interactive: true

  migrate:
    command: ["bin/rake", "db:migrate"]

  notifySlack:
    image: slack:21.3.4
    env:
      SLACK_CHANNEL: '#labs'
      SLACK_MESSAGE: "Do something {.Host}"

callbacks:
  preDeployment: [migrate]
  postDeployment: [notifySlack]
 